pipeline {
    agent any
    tools {
        maven "maven-3.9.6"
    }

    environment {
        // 确保这里的SONAR_TOKEN是您在Jenkins中配置的SonarQube token
        SONAR_TOKEN = credentials('newtoken')
    }

    stages {
        stage('Build') {
            steps {
                sh "mvn clean package -DskipTests"
            }
            post {
                always {
                    echo 'stage post always'
                }
                success {
                    echo 'pipeline post success'
                }
                failure {
                    echo 'pipeline post failure'
                }
            }
        }

        stage('Test') {
            steps {
                sh "mvn test jacoco:prepare-agent jacoco:report"
            }
            post {
                always {
                    jacoco(execPattern: '**/target/site/jacoco/jacoco.xml')
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                // 请确保这里的sonar.host.url指向您的SonarQube服务器的URL
                sh "mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN"
            }
        }
    }
}
