pipeline {
    agent any
    tools {
        maven "maven-3.9.6"
    }

    environment {
        SONAR_TOKEN = credentials('global_token')
    }

    stages {
        stage('Build') {
            steps {
                sh "cd jenkins-demo1 && mvn clean package -DskipTests"
            }
            post {
                always {
                    echo 'stage post always'
                }
                success {
                    echo 'pipeline post success'
                }
                failure {
                    echo 'pipeline post failure'
                }
            }
        }

        stage('Test') {
            steps {
                sh "cd jenkins-demo1 && mvn test jacoco:prepare-agent jacoco:report"
            }
            post {
                always {
                    jacoco(execPattern: '**/target/jacoco.exec')
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                sh "cd jenkins-demo1 && mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=http://localhost:9000"
            }
        }
    }
}
